[package]
name = "dioprocess"
version.workspace = true
edition.workspace = true

[dependencies]
dioxus = { version = "0.6", features = ["desktop"] }
ui = { path = "../ui" }

[build-dependencies]
embed-resource = "3.0.6"