[workspace]
resolver = "2"
members = [
    "crates/process",
    "crates/network",
    "crates/service",
    "crates/misc",
    "crates/ui",
    "crates/dioprocess",
]

[workspace.package]
version = "1.1.1"
edition = "2021"

